sudo: true
language: php

php:
 - 7.2

before_script:
 - echo | pecl install channel://pecl.php.net/yaml-2.0.2
 - git clone https://github.com/krakjoe/pthreads.git
 - cd pthreads
 - git checkout db8bc7fe2bfd79019c94f591eefa48bad4725a88
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install

script:
 - ./ci/travis.sh

notifications:
 email: false

before_deploy:
- mv plugins/Altay/Altay*.phar plugins/Altay/Altay.phar
- chmod +x ci/travis.sh
- chmod +x ci/lint.sh